<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class Coupon extends Model
{
    use HasFactory;

    protected $fillable = [
        'code',
        'slug',
        'apply_type',
        'amount',
        'started_at',
        'expired_at',
        'description',
        'status'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Coupon $coupon) {
            $coupon->code = slug($coupon->code);
        });

        static::updating(function (Coupon $coupon) {
            $coupon->code = slug($coupon->code);
        });
    }
}
