<?php

namespace App\Models;

use Eloquent;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Coupon
 * @mixin Eloquent
 */

class Coupon extends Model
{
    use HasFactory;

    const APPLY_TYPE = [
        0 => 'percent (%)',
        1 => 'fixed',
    ];
    protected $casts = [
        'started_at' => 'datetime',
        'expired_at' => 'datetime',
    ];
    protected $fillable = [
        'code',
        'slug',
        'apply_type',
        'amount',
        'started_at',
        'expired_at',
        'title',
        'status'
    ];

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function (Coupon $coupon) {
            $coupon->slug = slug($coupon->code);
        });

        static::updating(function (Coupon $coupon) {
            $coupon->slug = slug($coupon->code);
        });
    }

    public function scopeActive($query)
    {
        return $query->where('status', 1);
    }
}
